### ISSUE TITLE
SegFault and Crash on Gnome 3.32

### ISSUE THREAD

**Issue by edrose** [spin83/multi-monitors-add-on#86]
When this extension is running on Gnome 3.32 and only a single monitor is attached, it causes a segfault and complete crash of the shell when trying to open activities overview. When running on Wayland, the entire session is always lost. When running on XOrg, sometimes `gnome-shell` is able to restart in the background but sometimes the entire session is also lost. This does not happen when more monitors are plugged in. It's not possible to fix this without uninstalling the extension completely, since it's in an error state and therefore can't be disabled from the UI. It causes the crash even when in the error state.

System: Arch Linux
Gnome Shell: 3.32.0

Error messages from `journalctl`

```
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: JS ERROR: TypeError: this.actor is null
                                             _updateWorkspacesActualGeometry@resource:///org/gnome/shell/ui/workspacesView.js:647:13
                                             _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:566:9
                                             show@resource:///org/gnome/shell/ui/workspacesView.js:482:9
                                             show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                             _animateVisible@resource:///org/gnome/shell/ui/overview.js:527:9
                                             show@resource:///org/gnome/shell/ui/overview.js:513:9
                                             toggle@resource:///org/gnome/shell/ui/overview.js:636:13
                                             _initializeUI/<@resource:///org/gnome/shell/ui/main.js:190:13
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_render_resources: assertion 'width > 0 && height > 0' failed
Mar 18 13:33:49 ed-laptop audit[2575]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=7 pid=2575 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_color: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop gnome-shell[2575]: st_theme_node_get_border_width: assertion 'ST_IS_THEME_NODE (node)' failed
Mar 18 13:33:49 ed-laptop kernel: gnome-shell[2575]: segfault at 80 ip 00007f2666e52180 sp 00007ffd94a6b618 error 4 in libst-1.0.so[7f2666e52000+2d000]
Mar 18 13:33:49 ed-laptop kernel: Code: 7f 18 8b 77 7c 85 f6 7f 11 8b 4f 74 85 c9 7f 0a 8b 57 78 31 c0 85 d2 0f 9f c0 c3 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 <8b> 87 80 00 00 00 8b 97 84 00 00 00 f3 0f 10 15 b0 ec 02 00 89 c1
Mar 18 13:33:49 ed-laptop kernel: audit: type=1701 audit(1552916029.196:162): auid=1000 uid=1000 gid=1000 ses=7 pid=2575 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Mar 18 13:33:49 ed-laptop systemd[1]: Started Process Core Dump (PID 2993/UID 0).
Mar 18 13:33:49 ed-laptop audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-2993-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 18 13:33:49 ed-laptop kernel: audit: type=1130 audit(1552916029.216:163): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@1-2993-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

Backtrace from the core dump

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2666e52180 in ?? () from /usr/lib/gnome-shell/libst-1.0.so
[Current thread is 1 (Thread 0x7f265fe3d100 (LWP 2575))]
(gdb) bt
#0  0x00007f2666e52180 in  () at /usr/lib/gnome-shell/libst-1.0.so
#1  0x00007f2666e5b060 in  () at /usr/lib/gnome-shell/libst-1.0.so
#2  0x00007f2666e5dac7 in st_theme_node_paint () at /usr/lib/gnome-shell/libst-1.0.so
#3  0x00007f2666e60391 in st_widget_paint_background () at /usr/lib/gnome-shell/libst-1.0.so
#4  0x00007f2666e603bf in  () at /usr/lib/gnome-shell/libst-1.0.so
#5  0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#6  0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#7  0x00007f2667140e09 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#8  0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#9  0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#10 0x00007f2666e7e189 in  () at /usr/lib/gnome-shell/libst-1.0.so
#11 0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#12 0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#13 0x00007f2667140e09 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#14 0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#15 0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#16 0x00007f2666e7e189 in  () at /usr/lib/gnome-shell/libst-1.0.so
#17 0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#18 0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#19 0x00007f2667140e09 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#20 0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#21 0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#22 0x00007f2667140e09 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#23 0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#24 0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#25 0x00007f26670d073b in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#26 0x00007f2666f8b44f in  () at /usr/lib/libmutter-4.so.0
#27 0x00007f266713b054 in clutter_actor_continue_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#28 0x00007f26671407a4 in clutter_actor_paint () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#29 0x00007f26670d03f4 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#30 0x00007f26670928c8 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#31 0x00007f2667092f64 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#32 0x00007f2667093eab in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#33 0x00007f26670ecc64 in  () at /usr/lib/mutter-4/libmutter-clutter-4.so.0
#34 0x00007f2667a9b7bf in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#35 0x00007f2667a9d739 in  () at /usr/lib/libglib-2.0.so.0
#36 0x00007f2667a9e6d2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#37 0x00007f2666f55b8c in meta_run () at /usr/lib/libmutter-4.so.0
#38 0x000055aceb2343ab in  ()
#39 0x00007f2667fda223 in __libc_start_main () at /usr/lib/libc.so.6
#40 0x000055aceb23450e in  ()
```

**Comment by BloodyIron** [comment]
Any chance we can get this updated for gnome-shell 3.32? Crashing for me immediately too. :S

Really useful extension!

**Comment by palvarez89** [comment]
Installing the latest version from master branch (see the README.md) fixed it for me for now.
